name: Deploy to Staging

concurrency: 1

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - staging
    paths:
      - 'my_mlops_stack/**'
      - '.github/workflows/*.yml'
      
defaults:
  run:
    working-directory: ./my_mlops_stack

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy -t staging
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging

  feature_engineering:
    name: "Run Feature Engineering"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run write_feature_table_job -t staging --refresh-all 2>&1 | tee feature_engineering_output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging
  
  model_training:
    name: "Run Model Training"
    runs-on: ubuntu-latest

    needs:
      - feature_engineering

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run model_training_job -t staging --refresh-all 2>&1 | tee model_training_output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging
  
  batch_inference:
    name: "Run Batch Inference"
    runs-on: ubuntu-latest

    needs:
      - model_training

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run batch_inference_job -t staging --refresh-all 2>&1 | tee batch_inference-job_output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging 
            